# typed: false
# frozen_string_literal: true

# https://github.com/yohamta/homebrew-tap/blob/master/Formula/dagu.rb
# How to define a homebrew service: https://github.com/Homebrew/homebrew-services/blob/211ae5be9d965d6362ac10af863902a86153662d/lib/service/formula_wrapper.rb#L42


# This file was generated by GoReleaser. DO NOT EDIT.
class Dagu < Formula
  desc "A No-code workflow executor that runs DAGs defined in a simple YAML format"
  homepage "https://github.com/dagu-dev/dagu"
  version "1.13.0"
  license "GNU General Public License v3.0"

  on_macos do
    on_intel do
      url "https://github.com/dagu-dev/dagu/releases/download/v1.13.0/dagu_1.13.0_darwin_amd64.tar.gz"
      sha256 "42258b77cd2d5cfbce893ae83fe8d323895491fc25d6630a14955c1429feadd0"

      def install
        bin.install "dagu"
      end
    end
    on_arm do
      url "https://github.com/dagu-dev/dagu/releases/download/v1.13.0/dagu_1.13.0_darwin_arm64.tar.gz"
      sha256 "6559b86947d17ed2943dd167d70588d732c6cd86e490e06b16c57b8328331c56"

      def install
        bin.install "dagu"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dagu-dev/dagu/releases/download/v1.13.0/dagu_1.13.0_linux_amd64.tar.gz"
        sha256 "73cbae1a860ec6382f5cab922df4878bad97f455ec3cad2de35650aa19dfcdb3"

        def install
          bin.install "dagu"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dagu-dev/dagu/releases/download/v1.13.0/dagu_1.13.0_linux_arm64.tar.gz"
        sha256 "ec0b48fb4639de996487988eeaedf1829cf423b9248b2ea51f4db1da67996beb"

        def install
          bin.install "dagu"
        end
      end
    end
  end

  service do
    run [opt_bin/"dagu", "start-all"]
    keep_alive true
    error_log_path var/"log/dagu.log"
    log_path var/"log/dagu.log"
    working_dir var
  end
end
