# This file was generated by GoReleaser. DO NOT EDIT.
class Mmake < Formula
  desc "Go wrapper for forked version of TJ Holowaychuk's Mmake"
  homepage "https://github.com/zph/mmake"
  version "1.4.6"

  if OS.mac?
    url "https://github.com/zph/mmake/releases/download/v1.4.6/mmake_1.4.6_darwin_x86_64.tar.gz"
    sha256 "2aa70290f19ab5fefaf85c955303360228d29fd06840edb90e6403a21957ac7e"
  elsif OS.linux?
    url "https://github.com/zph/mmake/releases/download/v1.4.6/mmake_1.4.6_linux_x86_64.tar.gz"
    sha256 "7f037fc0e8ba262c6c970952bc17528fbdfb1d86d47412ed08f36e4a5d1bd14c"
  end

  def install
    bin.install "mmake"
  end

  test do
    system "#{bin}/mmake help"
  end
end
