# This file was generated by GoReleaser. DO NOT EDIT.
class Mmake < Formula
  desc "Go wrapper for forked version of TJ Holowaychuk's Mmake"
  homepage "https://github.com/zph/mmake"
  version "1.4.4"

  if OS.mac?
    url "http://github.mycompany.com/foo/bar/releases/v1.4.4/mmake_1.4.4_darwin_x86_64.tar.gz"
    sha256 "38c46c1ca5dc2d45c00749ca6a61d7f6581fe75d652f913433f43eb2316e0c20"
  elsif OS.linux?
    url "http://github.mycompany.com/foo/bar/releases/v1.4.4/mmake_1.4.4_linux_x86_64.tar.gz"
    sha256 "20884053c3ef672beba871263a0b07d5a6b4e402d0495d9d450a19fc9e0a04ec"
  end

  def install
    bin.install "mmake"
  end

  test do
    system "#{bin}/mmake help"
  end
end
